### ISSUE TITLE
Issues deploying aidr-manager

### ISSUE THREAD

**Issue by jmgtan** [qcri-social/AIDR#24]
I encountered the following error while trying to deploy aidr-manager:

```
[2015-05-01T07:44:36.958+0000] [glassfish 4.1] [SEVERE] [AS-WEB-GLUE-00192] [javax.enterprise.web] [tid: _ThreadID=44 _ThreadName=admin-listener(5)] [timeMillis: 1430466276958] [levelValue: 1000] [[
  Undeployment failed for context /AIDRFetchManager]]

[2015-05-01T07:44:36.996+0000] [glassfish 4.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=44 _ThreadName=admin-listener(5)] [timeMillis: 1430466276996] [levelValue: 1000] [[
  Exception while loading the app : CDI deployment failure:WELD-001408: Unsatisfied dependencies for type Set<Service> with qualifiers @Default
  at injection point [BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedConstructor] @Inject com.google.common.util.concurrent.ServiceManager(Set<Service>)
  at com.google.common.util.concurrent.ServiceManager.<init>(ServiceManager.java:0)

org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type Set<Service> with qualifiers @Default
  at injection point [BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedConstructor] @Inject com.google.common.util.concurrent.ServiceManager(Set<Service>)
  at com.google.common.util.concurrent.ServiceManager.<init>(ServiceManager.java:0)
```

Any advice on how to proceed?

**Comment by koushiksinha** [comment]
Hi,

We normally deploy aidr-manager to tomcat and the pom.xml dependency
parameters have been set accordingly.  Can u please attempt a deployment on
tomcat?

Otherwise,  you will have to experiment with 'compile' and 'provided'
options for the jersey and glassfish dependencies.

Regards,
Koushik

**Comment by kushalkantgoyal** [comment]
You can deploy aidr-manager by simply uncheck "Implicit CDI Enabled" while deploying on GF4.1

**Comment by jmgtan** [comment]
Managed to get it to work by disabling CDI:

`asadmin set configs.config.server-config.cdi-service.enable-implicit-cdi=false`
